FROM node:8-alpine

RUN apk add --no-cache yarn
RUN yarn global add @vue/cli

RUN mkdir /app
WORKDIR /app

COPY package.json /app/package.json
COPY yarn.lock /app/yarn.lock 
RUN yarn install

EXPOSE 8080