# Generated by Django 2.1.3 on 2018-11-10 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_year',
            new_name='birth_date',
        ),
    ]
