# Generated by Django 2.1.3 on 2018-11-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.CharField(max_length=300)),
                ('target', models.CharField(max_length=300)),
                ('indicator', models.CharField(max_length=300)),
                ('series', models.CharField(max_length=300)),
                ('source', models.TextField()),
                ('data', models.TextField()),
                ('min_year', models.IntegerField(null=True)),
                ('max_year', models.IntegerField(null=True)),
                ('oldest_year', models.IntegerField(null=True)),
                ('newest_year', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
