# Generated by Django 2.1.3 on 2018-11-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='unit',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='fact',
            name='unit_parsed',
            field=models.CharField(default='', max_length=300),
        ),
    ]
