# Generated by Django 2.1.3 on 2018-11-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0003_fact_fact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='custom_order',
            field=models.IntegerField(null=True),
        ),
    ]
