# Generated by Django 2.1.3 on 2018-11-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0004_fact_custom_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fact',
            options={'ordering': ('custom_order',)},
        ),
    ]
