# Generated by Django 2.1.3 on 2018-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0005_auto_20181110_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
