# Generated by Django 2.1.3 on 2018-11-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facts', '0006_fact_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='alert',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact',
            name='edu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact',
            name='love',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fact',
            name='sad',
            field=models.IntegerField(default=0),
        ),
    ]
