# Generated by Django 2.1.3 on 2018-11-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg_api', '0002_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='series',
            name='goal',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='series',
            name='indicator',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='series',
            name='target',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='series',
            name='uri',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='target',
            name='code',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='target',
            name='goal',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='target',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='target',
            name='uri',
            field=models.CharField(max_length=300),
        ),
    ]
