# Generated by Django 2.1.3 on 2018-11-09 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg_api', '0003_auto_20181109_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
