# Generated by Django 2.1.3 on 2018-11-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdg_api', '0004_geoarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPivotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.CharField(max_length=300)),
                ('target', models.CharField(max_length=300)),
                ('indicator', models.CharField(max_length=300)),
                ('series', models.CharField(max_length=300)),
                ('source', models.TextField()),
                ('data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
